# docker-compose up -d
# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest 
    container_name: lemp_nginx
    # маршрутизируем порты
    ports:
      - "80:80" 
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      #-./hosts:/etc/nginx/nginx.conf
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx/log
      #- ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/:/etc/nginx/sites-available
      - ./etc/nginx/:/etc/nginx/sites-enabled
    
    # nginx должен общаться с php контейнером
    links:
      - php
  
  php:
      # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
      # этот образ будет общаться с mysql
    links:
        - mysql
      # монтируем директорию с проектами
    volumes:
        - ./www:/var/www
  

  mysql:
      image: mysql
      container_name: lemp_mysql
      ports:
        - "3306:3306"
      expose:
      # Opens port 3306 on the container
        - '3306'
      # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
      # (this is just an example, not intended to be a production configuration)
      volumes:
        - ./etc/mysql:/etc/mysql/my.cnf
        - ./etc/mysql:/etc/mysql/conf.d
        - ./etc/mysql:/etc/mysql/mysql.conf.d 
        - ./data:/docker-entrypoint-initdb.d
        - ./mysql:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
        #- ./mysql-files:/var/lib/mysql-files
      command: --default-authentication-plugin=mysql_native_password
      #restart: always
      # задаем пароль для root пользователя
      # заливку дампа сайта и создание пользователя для доступа к базе снаружи будем делать позже
      environment:
        MYSQL_DATABASE: db
        # So you don't have to use root, but you can if you like
        MYSQL_USER: user
        # You can use whatever password you like
        MYSQL_PASSWORD: admin
        # Password for root access
        MYSQL_ROOT_PASSWORD: admin
  pma:
     image: phpmyadmin/phpmyadmin
     container_name: lemp_phpmyadmin
     links:
       - mysql:mysql
     ports:
       - 8001:80
     #restart: always
     environment:
           PMA_HOST: mysql
           MYSQL_USERNAME: root
           MYSQL_ROOT_PASSWORD: root


